web:
  build: .
  links:
    - mysql
  ports:
    - "3001:3000"
dev:
  image: ruby:2.2
  links:
    - mysql
  ports:
    - "3000:3000"
  working_dir: /usr/src/app
  volumes:
    - .:/usr/src/app
  command: /bin/bash
  stdin_open: true
  tty: true
  user: 1000
  environment:
    HOME: /usr/src/app
    BUNDLE_PATH: /usr/src/app/.bundle
    BUNDLE_APP_CONFIG: /usr/src/app/.bundle
mysql:
  image: mysql
  environment:
    MYSQL_ROOT_PASSWORD: secret
    MYSQL_USER: user
    MYSQL_PASSWORD: pass
    MYSQL_DATABASE: workshop